/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "square.h"

bool_t
xdr_square_in (XDR *xdrs, square_in *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->client_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cur_question))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->send_marks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->choice))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->check))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->update_marks))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->client_id);
			IXDR_PUT_LONG(buf, objp->cur_question);
			IXDR_PUT_LONG(buf, objp->send_marks);
			IXDR_PUT_LONG(buf, objp->choice);
			IXDR_PUT_LONG(buf, objp->check);
			IXDR_PUT_LONG(buf, objp->update_marks);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->client_id))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->cur_question))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->send_marks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->choice))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->check))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->update_marks))
				 return FALSE;
		} else {
			objp->client_id = IXDR_GET_LONG(buf);
			objp->cur_question = IXDR_GET_LONG(buf);
			objp->send_marks = IXDR_GET_LONG(buf);
			objp->choice = IXDR_GET_LONG(buf);
			objp->check = IXDR_GET_LONG(buf);
			objp->update_marks = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->client_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cur_question))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->send_marks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->choice))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->check))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->update_marks))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_square_out (XDR *xdrs, square_out *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->ans, 500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->question, 500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->RANK))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->last_question))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->last_marks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->is_finished))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->RANK);
			IXDR_PUT_LONG(buf, objp->last_question);
			IXDR_PUT_LONG(buf, objp->last_marks);
			IXDR_PUT_LONG(buf, objp->is_finished);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->ans, 500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->question, 500,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->RANK))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->last_question))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->last_marks))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->is_finished))
				 return FALSE;
		} else {
			objp->RANK = IXDR_GET_LONG(buf);
			objp->last_question = IXDR_GET_LONG(buf);
			objp->last_marks = IXDR_GET_LONG(buf);
			objp->is_finished = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->ans, 500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->question, 500,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->RANK))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->last_question))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->last_marks))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->is_finished))
		 return FALSE;
	return TRUE;
}
